Promotion Phase

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -263,15 +263,6 @@ jobs:
           working_directory: ./backend
           command: |
             npm run migrations > migration
-      # - run:
-      #     name: Send migration status to kvdb.io
-      #     working_directory: ./backend
-      #     command: |
-      #       if grep -q "has been executed successfully" migrations_dump.txt
-      #       then
-      #         curl https://kvdb.io/8DFRWBM789FENXhdPGxQ3e/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-      #       fi
-      #       echo "WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}"
       - destroy_environment:
           id: ${CIRCLE_WORKFLOW_ID:0:7}
           when: on_fail
@@ -346,61 +337,83 @@ jobs:
           id: ${CIRCLE_WORKFLOW_ID:0:7}
           when: on_fail
 
-  smoke-test:
-    executor: python
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run:
-          name: Install dependencies
-          working_directory: /tmp
-          command: |
-            apk add --update curl nodejs npm
-            pip install awscli
-      - run:
-          name: Backend smoke test.
-          working_directory: ./backend
-          command: |
-            BACKEND_IP=$(aws ec2 describe-instances \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --output text)
-            export API="http://${BACKEND_IP}:3030"
-            echo "${API}"
-            if curl "${API}/api/status" | grep "ok"
-            then
-              exit 0
-            else
-              exit 1
-            fi
-      - run:
-          name: Frontend smoke test.
-          working_directory: ./backend
-          command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com/index.html"
-            curl -s ${URL} | grep -q "Welcome"
-      - destroy_environment:
-          id: ${CIRCLE_WORKFLOW_ID:0:7}
-          when: on_fail
-      - revert_migrations:
-          id: ${CIRCLE_WORKFLOW_ID:0:7}
-          when: on_fail
+  # smoke-test:
+  #   executor: python
+  #   steps:
+  #     - checkout
+  #     - attach_workspace:
+  #         at: .
+  #     - run:
+  #         name: Install dependencies
+  #         working_directory: /tmp
+  #         command: |
+  #           apk add --update curl nodejs npm
+  #           pip install awscli
+  #     - run:
+  #         name: Backend smoke test.
+  #         working_directory: ./backend
+  #         command: |
+  #           BACKEND_IP=$(aws ec2 describe-instances \
+  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+  #             --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+  #             --output text)
+  #           export API="http://${BACKEND_IP}:3030"
+  #           echo "${API}"
+  #           if curl "${API}/api/status" | grep "ok"
+  #           then
+  #             exit 0
+  #           else
+  #             exit 1
+  #           fi
+  #     - run:
+  #         name: Frontend smoke test.
+  #         working_directory: ./backend
+  #         command: |
+  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.us-east-1.amazonaws.com/index.html"
+  #           if curl -s ${URL} | grep -q "Welcome"
+  #           then
+  #             exit 1
+  #           else
+  #             exit 1
+  #           fi
+  #     - destroy_environment:
+  #         id: ${CIRCLE_WORKFLOW_ID:0:7}
+  #         when: on_fail
+  #     - revert_migrations:
+  #         id: ${CIRCLE_WORKFLOW_ID:0:7}
+  #         when: on_fail
 
-#   cloudfront-update:
-#     docker:
-#       # Docker image here that supports AWS CLI
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure
+  # cloudfront-update:
+  #   executor: aws
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           yum install -y tar gzip curl
+  #           curl -sL https://rpm.nodesource.com/setup_10.x | bash -
+  #           yum install -y nodejs
+  #     - run:
+  #         name: Store old WorkflowID in memstash for cleanup phase
+  #         working_directory: ./.circleci/files
+  #         command: |
+  #           aws cloudformation \
+  #             list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+  #             --no-paginate --output text >> old_workflow_id.txt
+  #           cat old_workflow_id.txt
+
+  #     - run:
+  #         name: Update cloudfront distribution
+  #         working_directory: ./.circleci/files
+  #         command: |
+  #           aws cloudformation deploy \
+  #             --template-file cloudfront.yml \
+  #             --stack-name udapeople-cloudfront-production \
+  #             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+  #             --tags project=udapeople
+  #     - revert_migrations:
+  #         id: ${CIRCLE_WORKFLOW_ID:0:7}
+  #         when: on_fail
 
 # cleanup:
 #   docker:
@@ -471,11 +484,12 @@ workflows:
       - deploy-frontend:
           requires:
             - run-migrations
-      - smoke-test:
-          requires:
-            - deploy-backend
-            - deploy-frontend
+      # - smoke-test:
+      #     requires:
+      #       - deploy-backend
+      #       - deploy-frontend
       # - cloudfront-update:
-      #     requires: [smoke-test]
+      #     requires:
+      #       - smoke-test
       # - cleanup:
       #     requires: [cloudfront-update]
